# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7b84ed8a14dcc86b56e7ea74dda62290525c4d8f4e045b46c244816e3f9235b44135cb1b42af73dd2251476ea23fe1d206b2175c05560e4ad2c2ee015f2205

test:
  secret_key_base: 43bffebbdfe0bb16b3685f87aefdc431b6fa80afc6278ae3fe8043836da56aa915cc3682210cea6a6399cd48dad141bb72502894ac1e6d1476154eb0e0c50eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
